---
# tasks file for docker

- include: centos.yml
  when: ansible_os_family == "RedHat"

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Disable SELINUX
  selinux:
    policy: targeted
    state: disabled
  notify:
    - reboot      