---
    - name: install nginx
      hosts: all
      become: true
      user: root
      tasks:
        - name: Allow Consul ports
          firewalld:
            port: "{{ item }}"
            zone: public
            permanent: yes
            immediate: yes
            state: enabled
          with_items:
            - '8600/tcp'
            - '8600/udp'
            - '8500/tcp'
            - '8301/tcp'
            - '8301/udp'
            - '8302/tcp'
            - '8302/udp'
            - '8300/tcp'